### ISSUE TITLE
请问怎么安装？

### ISSUE THREAD

**Issue by valuex** [wangzhfeng/MarkdownViewer#1]
请问怎么安装？

**Comment by wangzhfeng** [comment]
在[发布版本](https://github.com/wangzhfeng/MarkdownViewer/releases)中有说明

安装步骤：

- 安装TcPluginSetup.msi，增加Total Commander的.NET接口；
- 在Total Commander中打开MarkdownViewer.zip，提示安装该插件，按照指示操作即可。
