### ISSUE TITLE
not working with Total Commander 9.51

### ISSUE THREAD

**Issue by piterq** [wangzhfeng/MarkdownViewer#12]
Not working with Total Commander 9.51:
- x64 version kills TotalCommander while installing plugin
- x86 version reports "External exception E0434352" while installing plugin
Tested on Windows 10 x64 Pro 1909.

**Comment by wangzhfeng** [comment]
I cannot reproduce the issue, following image is my test result.
Which version did you try?

![image](https://user-images.githubusercontent.com/2019930/108452245-26231080-72a3-11eb-98b4-18bf76d62c55.png)

**Comment by piterq** [comment]
I'm using latest version (0.3). It simply can't be installed. This is what happens when I press ENTER on MarkdownViewer.zip file (32-bit Total Commander version):

![image](https://user-images.githubusercontent.com/59413148/108475078-852b5a00-7290-11eb-8de2-dcd8b4c8c3ce.png)

**Comment by wangzhfeng** [comment]
I test on 32-bit Total Commander, it runs ok. The plugin dependents on [TC.NET interface v1.4](https://sourceforge.net/projects/tcdotnetinterface/files/), did you installed it? If not, please download and install, then install the plugin.

**Comment by piterq** [comment]
I've installed TcPluginSetup.msi. Now MarkdownViewer is installing correctly and is working fine on 64-bit Total Commander.
Edit: maybe you should mention something about this prerequisite in readme.
