### ISSUE TITLE
Esc不会退出窗口

### ISSUE THREAD

**Issue by void285** [wangzhfeng/MarkdownViewer#4]
你好，我在用的多数Lister查看文件时可以按Esc退出窗口，但这个插件不会响应这个操作，似乎也没有配置的地方。
我不是很确定Esc关闭Lister是不是默认配置，还是我用的配置文件里设置的。如果这个插件没有添加这个功能，是否可以加上呢？

**Comment by wangzhfeng** [comment]
您好，我还是个.net新手，而且基于.net开发插件的资料非常少，所以还没有实现，不过我正在努力，因为我自己也正苦恼这件事情

**Comment by void285** [comment]
@wangzhfeng 加油，期待！

**Comment by wangzhfeng** [comment]
已经修复了，见[v0.2](https://github.com/wangzhfeng/MarkdownViewer/releases/tag/v0.2)。

**Comment by void285** [comment]
👍
Wonderful work
