### ISSUE TITLE
您好，请问怎么安装？

### ISSUE THREAD

**Issue by jieYM** [wangzhfeng/MarkdownViewer#8]
您好，怎么安装？

**Comment by wangzhfeng** [comment]
1、安装TcPluginSetup.msi，下载[链接](https://sourceforge.net/projects/tcdotnetinterface/files/)，增加Total Commander的.NET接口；
2、在Total Commander中打开MarkdownViewer.zip，提示安装该插件，按照指示操作即可。

**Comment by jieYM** [comment]
> 1、安装TcPluginSetup.msi，下载[链接](https://sourceforge.net/projects/tcdotnetinterface/files/)，增加Total Commander的.NET接口；
> 2、在Total Commander中打开MarkdownViewer.zip，提示安装该插件，按照指示操作即可。

----
安装成功了，但.md文件还是按文本文件显示，Total Commander重启了还是没用

**Comment by Vincendovich** [comment]
> > 1、安装TcPluginSetup.msi，下载[链接](https://sourceforge.net/projects/tcdotnetinterface/files/)，增加Total Commander的.NET接口；
> > 2、在Total Commander中打开MarkdownViewer.zip，提示安装该插件，按照指示操作即可。
> 
> 安装成功了，但.md文件还是按文本文件显示，Total Commander重启了还是没用

需要在lister的列表中，把这个lister挑到更靠前的序列

**Comment by jieYM** [comment]
> > > 1、安装TcPluginSetup.msi，下载[链接](https://sourceforge.net/projects/tcdotnetinterface/files/)，增加Total Commander的.NET接口；
> > > 2、在Total Commander中打开MarkdownViewer.zip，提示安装该插件，按照指示操作即可。
> > 
> > 
> > 安装成功了，但.md文件还是按文本文件显示，Total Commander重启了还是没用
> 
> 需要在lister的列表中，把这个lister挑到更靠前的序列

上移到前面成功了，多谢！
